using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using System.IO.Compression;

namespace rbkApiModules.Commons.Core.CodeGeneration;

[Route("api/code-generator")]
[ApiController]
[IgnoreOnCodeGeneration]
[AllowAnonymous]
public class CodeGeneratorController : BaseController
{
    private readonly IWebHostEnvironment _environment;

    public CodeGeneratorController(IWebHostEnvironment environment)
    {
        _environment = environment;
    }

    [HttpGet]
    public async Task<ActionResult> Get(bool directUpdate, string projectId, CancellationToken cancellation)
    {
        String basePath;
        if (directUpdate)
        {
            var codePath = GetAutogeneratedFolder("frontend", projectId);

            if (!Directory.Exists(codePath))
            {
                codePath = GetAutogeneratedFolder("front", projectId);

                if (!Directory.Exists(codePath))
                {
                    return Ok($"Could not locate the auto-generated folder under '{codePath}'");
                }
            }

            try
            {
                var files = Directory.GetFiles(codePath, "*.*", SearchOption.AllDirectories);

                if (files.Any(x => Path.GetExtension(x).ToLower() != ".ts"))
                {
                    return Ok("Aborting code generation because we might be in the wrong path: " + codePath.First());
                }

                foreach (var file in files)
                {
                    System.IO.File.Delete(file);
                }
            }
            catch (Exception ex)
            {
                return Ok("Não foi possível apagar os arquivos no repositório");
            }

            basePath = codePath;
        }
        else
        {
            basePath = Path.Combine(_environment.ContentRootPath, "wwwroot", "_temp", Guid.NewGuid().ToString());
        }

        if (directUpdate)
        {
            var codeGenerator = new AngularCodeGenerator(projectId, basePath);
            codeGenerator.Generate();

            return Ok("Arquivos atualizados com sucesso :)");
        }
        else
        {
            var codeGenerator = new AngularCodeGenerator(projectId, Path.Combine(basePath, "code"));
            codeGenerator.Generate();

            var zipFile = Path.Combine(basePath, "code.zip");
            ZipFile.CreateFromDirectory(Path.Combine(basePath, "code"), zipFile);

            var memory = new MemoryStream();
            using (var stream = new FileStream(zipFile, FileMode.Open))
            {
                await stream.CopyToAsync(memory);
            }
            memory.Position = 0;

            Directory.Delete(basePath, true);

            return File(memory, "application/zip", "code.zip");
        }
    }

    private string GetAutogeneratedFolder(string frontFolder, string projectId)
    {
        var searchString = Path.Combine(frontFolder, "src", "app", "auto-generated");

        if (!String.IsNullOrEmpty(projectId))
        {
            searchString = Path.Combine(frontFolder, projectId, "src", "app", "auto-generated");
        }

        var applicationPath = new DirectoryInfo(_environment.ContentRootPath);
        var codePath = Path.Combine(applicationPath.Parent.Parent.FullName, searchString);

        return codePath;
    }
}
