using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using rbkApiModules.Commons.Core.Localization;
using System.IO.Compression;

namespace rbkApiModules.Commons.Core.CodeGeneration;

[Route("api/code-generator")]
[ApiController]
[IgnoreOnCodeGeneration]
[AllowAnonymous]
public class CodeGeneratorController : BaseController
{
    private readonly IWebHostEnvironment _environment;
    private readonly ILocalizationService _localization;

    public CodeGeneratorController(IWebHostEnvironment environment, ILocalizationService localization)
    {
        _localization = localization;
        _environment = environment;
    }

    /// <summary>
    /// Generates Angular code for a specified project and either updates the target directory directly or provides a downloadable ZIP file.
    /// </summary>
    /// <param name="directUpdate">
    /// If <c>true</c>, the generated code will be written directly to the target directory. 
    /// If <c>false</c>, the generated code will be packaged as a ZIP file and returned for download.
    /// </param>
    /// <param name="projectId">
    /// (optional) The identifier of the project for which code should be generated. 
    /// </param>
    /// <param name="relativePath">
    /// The relative path to the <c>auto-generated</c> folder within the project. Must include "auto-generated" if <paramref name="projectId"/> is provided and start at the root of the repository
    /// </param>
    /// <param name="isLegacySmz">
    /// Indicates whether to use legacy code generation logic for SMZ projects (prior or up to version ngx-smz-ui@17.3.0 is considered a legacy version).
    /// </param>
    /// <returns>
    /// Returns an <see cref="ActionResult"/>. If <paramref name="directUpdate"/> is <c>true</c>, returns a status message as a string. 
    /// If <paramref name="directUpdate"/> is <c>false</c>, returns a ZIP file containing the generated code.
    /// </returns>
    /// <remarks>
    /// - If <paramref name="directUpdate"/> is <c>true</c>, the method attempts to clean the target directory before generating new code.
    /// - If <paramref name="directUpdate"/> is <c>false</c>, the generated code is placed in a temporary directory and returned as a ZIP file.
    /// - Returns <c>BadRequest</c> if the <paramref name="relativePath"/> does not contain "auto-generated" when <paramref name="projectId"/> is provided.
    /// </remarks>
    [HttpGet]
    public async Task<ActionResult> Get(bool directUpdate, string projectId, string relativePath, bool isLegacySmz, CancellationToken cancellation)
    {
        CodeGenerationOptions.IsSmzLegacy = isLegacySmz;

        if (!String.IsNullOrEmpty(projectId))
        {
            relativePath = relativePath.Replace("/", "\\");

            if (!relativePath.Contains("auto-generated"))
            {
                return BadRequest("O caminho relativo deve ser da pasta raiz até a pasta auto-generated");
            }
        }

        String basePath;
        if (directUpdate)
        {
            var codePath = GetAutogeneratedFolder("frontend", projectId, relativePath);
            Logger.Debug("Looking for repository in the following path: {path}", codePath);

            if (!Directory.Exists(codePath))
            {
                Logger.Debug("Path not found, trying another option");

                codePath = GetAutogeneratedFolder("front", projectId, relativePath);

                Logger.Debug("Looking for repository in the following path: {path}", codePath);

                if (!Directory.Exists(codePath))
                {
                    return Ok($"Could not locate the auto-generated folder under '{codePath}'");
                }
            }
            else
            {
                Logger.Debug("Path found, using it!");
            }

            try
            {
                var files = Directory.GetFiles(codePath, "*.*", SearchOption.AllDirectories);

                if (files.Any(x => Path.GetExtension(x).ToLower() != ".ts"))
                {
                    Logger.Debug("Could not find any TypeScript file, aborting for security reasons");

                    return Ok("Aborting code generation because we might be in the wrong path: " + codePath.First());
                }

                foreach (var file in files)
                {
                    System.IO.File.Delete(file);
                }
            }
            catch (Exception ex)
            {
                Logger.Debug(ex, "Could not delete all files from repository");

                return Ok("Não foi possível apagar os arquivos no repositório");
            }

            basePath = codePath;
        }
        else
        {
            basePath = Path.Combine(_environment.ContentRootPath, "wwwroot", "_temp", Guid.NewGuid().ToString());

            Logger.Debug("Using the download option, files will be save in a temporary path: {path}", basePath);
        }

        if (directUpdate)
        {
            var codeGenerator = new AngularCodeGenerator(projectId, basePath, _localization);
            codeGenerator.Generate();

            return Ok("File successfully updated :)");
        }
        else
        {
            var codeGenerator = new AngularCodeGenerator(projectId, Path.Combine(basePath, "code"), _localization);
            codeGenerator.Generate();

            var zipFile = Path.Combine(basePath, "code.zip");
            ZipFile.CreateFromDirectory(Path.Combine(basePath, "code"), zipFile);

            var memory = new MemoryStream();
            using (var stream = new FileStream(zipFile, FileMode.Open))
            {
                await stream.CopyToAsync(memory);
            }
            memory.Position = 0;

            Directory.Delete(basePath, true);

            return File(memory, "application/zip", "code.zip");
        }
    }

    private string GetAutogeneratedFolder(string frontFolder, string projectId, string relativePath)
    {
        var applicationPath = new DirectoryInfo(_environment.ContentRootPath);
        string codePath;

        if (String.IsNullOrEmpty(relativePath))
        {
            var searchString = Path.Combine(frontFolder, "src", "app", "auto-generated");

            if (!String.IsNullOrEmpty(projectId))
            {
                searchString = Path.Combine(frontFolder, projectId, "src", "app", "auto-generated");
            }

            codePath = Path.Combine(applicationPath.Parent.Parent.FullName, searchString);
        }
        else
        {
            codePath = Path.Combine(applicationPath.Parent.Parent.FullName, relativePath);
        }

        return codePath;
    }
}

public static class CodeGenerationOptions
{
    public static bool IsSmzLegacy { get; set; } = false;
}