using Microsoft.AspNetCore.Http;
using Microsoft.Extensions.Logging;

namespace rbkApiModules.Commons.Core;

public class RequestContextLoggerMiddleware
{
    private readonly RequestDelegate _next;
    private readonly ILogger<RequestContextLoggerMiddleware> _logger;

    public RequestContextLoggerMiddleware(RequestDelegate next, ILogger<RequestContextLoggerMiddleware> logger)
    {
        _logger = logger;
        _next = next;
    }

    public async Task Invoke(HttpContext httpContext)
    {
        var correlationToken = "AutoGenerated -> " + Guid.NewGuid().ToString();

        httpContext.Request.Headers.TryGetValue("correlation-token", out var token);

        if (token.Count > 0)
        {
            correlationToken = token.First();
        }

        using (_logger.BeginScope(new Dictionary<string, object>
        {
            ["CorrelationToken"] = correlationToken
        }))
        {
            await _next(httpContext);
        }
    }
}