export const MAIN_LAYOUT_PATH = '';
export const HOME_PATH = '';
export const SEARCH_PATH = 'search';
export const DASHBOARD_PATH = 'dashboard';
export const DIAGNOSTICS_PATH = 'diagnostics';
export const ANALYTICS_PATH = 'analytics';
export const ADMIN_PATH = 'admin';
export const PERFORMANCE_PATH = 'performance';
export const LOGIN_PATH = 'login';
export const ERROR_PAGE_PATH = 'error';



export const AUTHENTICATED_HOME_ROUTE = ['/'];
export const HOME_PAGE_ROUTE = [MAIN_LAYOUT_PATH, HOME_PATH];
export const ANALYTICS_SEARCH_PAGE_ROUTE = [MAIN_LAYOUT_PATH, ANALYTICS_PATH, SEARCH_PATH];
export const ANALYTICS_DASHBOARD_PAGE_ROUTE = [MAIN_LAYOUT_PATH, ANALYTICS_PATH, DASHBOARD_PATH];
export const ANALYTICS_ADMIN_PAGE_ROUTE = [MAIN_LAYOUT_PATH, ANALYTICS_PATH, ADMIN_PATH];
export const ANALYTICS_PERFORMANCE_PAGE_ROUTE = [MAIN_LAYOUT_PATH, ANALYTICS_PATH, PERFORMANCE_PATH];
export const DIAGNOSTICS_SEARCH_PAGE_ROUTE = [MAIN_LAYOUT_PATH, DIAGNOSTICS_PATH, SEARCH_PATH];
export const DIAGNOSTICS_DASHBOARD_PAGE_ROUTE = [MAIN_LAYOUT_PATH, DIAGNOSTICS_PATH, DASHBOARD_PATH];
export const DIAGNOSTICS_ADMIN_PAGE_ROUTE = [MAIN_LAYOUT_PATH, DIAGNOSTICS_PATH, ADMIN_PATH];
export const DIAGNOSTICS_PERFORMANCE_PAGE_ROUTE = [MAIN_LAYOUT_PATH, DIAGNOSTICS_PATH, PERFORMANCE_PATH];
export const LOGIN_PAGE_ROUTE = [LOGIN_PATH];

