name: .NET

on:
  workflow_dispatch 

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
#    - name: Setup .NET
#      uses: actions/setup-dotnet@v1
#      with:
#        dotnet-version: 5.0.x
    - name: Echo test
      run: echo "Test"
    - name: Version test
      run: ./@Tools/VersionUpdater.exe
