on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

name: Create Release and Publish

jobs:
  release:
    name: Create Release
    runs-on: windows-latest
    if: "!contains(github.event.head_commit.message, '/^Release d+.d+.d+.*/')"
    steps:
      - uses: actions/checkout@v2
      - uses: FranzDiebold/github-env-vars-action@v1.2.0
      - name: Checkout Code
        run: |
          git config user.email "ci@github.com"
          git config user.name "ci"
          git remote set-url --push origin "https://github.com/rbasniak/rbk-api-modules.git"
          git reset --hard
          git clean -fd
      - name: Update Version
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          npm ci
          npx release-it --ci
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.x
      - name: Install dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --configuration Debug --no-restore
      - name: Create NuGet Package
        run: dotnet pack -c Debug --include-symbols --include-source
        working-directory: .
      - name: Publish Nuget Package
        run: dotnet nuget push **/*.symbols.nupkg --api-key ${{ secrets.nuget_api_key }} --source https://api.nuget.org/v3/index.json
