on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

name: Create Release

jobs:
  build:
    name: Create Release
    runs-on: windows-latest
    if: "!contains(github.event.head_commit.message, '/^Release d+.d+.d+.*/')"
    steps:
      - uses: actions/checkout@v2
      - name: Checkout Code
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}          
        run: |
          echo Setting git user
          echo $GITHUB_REPOSITORY
          echo ${{ GITHUB_REPOSITORY }}
          git config user.email "ci@github.com"
          git config user.name "ci"
          git remote set-url --push origin "https://github.com/$GITHUB_REPOSITORY.git"
          git reset --hard
          git clean -fd
          git checkout $GITHUB_REF_NAME
          git pull origin $GITHUB_REF_NAME
      - name: Update Version
        run: |
          npm ci
          npx release-it --ci      
          
