on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

name: Create Release and Publish

jobs:
  release:
    name: Create Release
    runs-on: windows-latest
    if: "!contains(github.event.head_commit.message, '/^Release d+.d+.d+.*/')"
    steps:
      - uses: actions/checkout@v2
      - name: Checkout Code
        run: |
          git config user.email "ci@github.com"
          git config user.name "ci"
          git remote set-url --push origin "https://github.com/rbasniak/rbk-api-modules.git"
          git reset --hard
          git clean -fd
          git checkout $GITHUB_REF_NAME
          git pull origin $GITHUB_REF_NAME
      - name: Update Version
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          npm ci
          npx release-it --ci